---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - python-mysqldb
   - mysql-server
   
- name: setup root password
  debconf: name='sqlserver' question='sqlserver/root_password' value={{'123456'}} vtype='password'

- name: root-password again
  debconf: name='sqlserver' question='sqlserver/root_password_again' value={{'123456'}} vtype='password'

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
